# Generated by Django 4.1.3 on 2023-05-26 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('available_count', models.IntegerField()),
                ('hidden', models.BooleanField(default=False)),
                ('rate', models.FloatField(default=0.0)),
                ('price', models.FloatField()),
                ('photo', models.ImageField(blank=True, upload_to='')),
            ],
        ),
    ]
